version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.10.3
        environment:
          MIX_ENV: test
          DATABASE_URL: postgres://countdown@localhost/countdown_test
      - image: circleci/postgres:10.12
        environment:
          POSTGRES_USER: countdown
          POSTGRES_DB: countdown_test
          POSTGRES_PASSWORD:
    working_directory: ~/app
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: curl https://pre-commit.com/install-local.py | python -

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix deps.get
      - run: pre-commit run --all-files

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
